### ISSUE TITLE
Support for old versions?

### ISSUE THREAD

**Issue by gmunkhbaatarmn** [ionelmc/python-appengine-sdk#1]
For some reason I'd like to use older version. In example:
`pip install appengine-sdk==1.9.15`

Current packaging supports just a latest version. What are you planning about support for old versions?

**Reference:**
Currently uploaded versions on pypi: https://pypi.python.org/simple/appengine-sdk/

```
appengine_sdk-1.9.18-py2-none-any.whl
appengine_sdk-1.9.18.post1-py2-none-any.whl
appengine_sdk-1.9.18.post2-py2-none-any.whl
appengine_sdk-1.9.19.post0-py2-none-any.whl
appengine_sdk-1.9.19.post1-py2-none-any.whl
appengine_sdk-1.9.19.post2-py2-none-any.whl
appengine_sdk-1.9.19.post3-py2-none-any.whl
```

**Comment by ionelmc** [comment]
Hey, If you need a specific version I can make a build and upload it. 

I didn't upload old releases cause I don't need them and I'd have to test them.

So you need `1.9.15` specifically?

**Comment by gmunkhbaatarmn** [comment]
Yes. Specially need `1.9.15` because of command: `old_dev_appserver.py`.
(For coverage integration, didn't found way to integrate new `dev_appserver.py` with coverage).

Thank you for build and upload requested version.

This URLs may help your work:
- https://storage.googleapis.com/appengine-sdks/deprecated/1915/google_appengine_1.9.15.zip
- https://github.com/gmunkhbaatarmn/python-appengine-sdk/commit/ee1b28a63a3ca898f9fc465f0e6df2e48d1e7535

**Comment by ionelmc** [comment]
Worth asking: is the coverage issue is the only thing blocking you from using latest sdk? How does it fail on the new sdk? How do you run the coverage module?

**Comment by gmunkhbaatarmn** [comment]
After run:
`coverage run dev_appserver.py project_root`
Can't collect coverage datas. 

> This doesn't work on current versions of GAE. They do some sandboxing within the code run for GAE (eg disable loading of binary modules, remove modules and methods not supported on the servers). coverage now produces data for everything except the actual application code!
> Source: http://stackoverflow.com/q/5800674/287255

But by using `old_dev_appserver.py` [can collect](http://stackoverflow.com/a/18691320/287255) coverage datas.
So reason of using 1.9.15 is, after v1.9.15 (from v1.9.16) `old_dev_appserver.py` not included in App Engine SDK.

Here is my currently using coverage running script:

```
coverage run -p --source=./ old_dev_appserver . --skip_sdk_update_check --clear_datastore --use_sqlite --port=8081 &> dev_appserver.log &
coverage run -p tests.py --source=./
coverage combine
coverage report ./*.py ./modules/*.py
```

**Comment by ionelmc** [comment]
The SO question, is that yours?

I also had some trouble with the new sandboxing code (I had the SDK installed in a virtualenv in the project's root, nothing worked properly because I had the virtualenv path excluded in app.yaml).

Could the location be the problem?

**Comment by gmunkhbaatarmn** [comment]
> The SO question, is that yours?

No. But I has same problem with question asker.

> I also had some trouble with the new sandboxing code (I had the SDK installed in a virtualenv in the project's root, nothing worked properly because I had the virtualenv path excluded in app.yaml).
> 
> Could the location be the problem?

I guess problem is not related with virtualenv. By feature `dev_appserver.py` is running app code in sandbox mode and therefore not produce coverage data.

But `old_dev_appserver.py` not running app code in sandbox mode and produce coverage data.
If you use `old_dev_appserver.py` instead of `dev_appserver.py` then coverage data will produce.

**Comment by ionelmc** [comment]
> I guess problem is not related with virtualenv. By feature dev_appserver.py is running app code in sandbox mode and therefore not produce coverage data.

AFAIK, the new sandboxed runner uses subprocesses so you have to use the tricks indicated here: http://nedbatchelder.com/code/coverage/subprocess.html

**Comment by gmunkhbaatarmn** [comment]
I tried to integrate coverage subprocess with `dev_appserver.py`. But didn't found a any proper way.
If you resolved with subprocess please suggest your solution.

**Comment by ionelmc** [comment]
The coverage package needs to be part of your app (not excluded) otherwise the sandbox importers GAE has will prevent it from importing.

**Comment by gmunkhbaatarmn** [comment]
Thanks for suggesting solution. But I'm not successful on subprocess solution and still prefering to use `old_dev_appserver` for coverage report.

If you not interested in upload old version for avoid unnecessary tasks, that's okay.

**Comment by ionelmc** [comment]
Sorry, I didn't want to turn you down. It's just that fixing the problem with coverage is just much more interesting and using old sdk seems like a bad idea long term (inevitably you'll want some features newer sdk has).

Plus you already have published that older sdk yourself. 

I can publish it too, if you really want that. It wasn't clear if that was the only thing you wanted, or it you want some help with the coverage issue. So, is that the only thing you want?

**Comment by gmunkhbaatarmn** [comment]
Yes, only needed thing is coverage integration.

So what's your solution for integrating coverage with App Engine?
And that solution working fine without virtual env?

**Comment by ionelmc** [comment]
Ok, just to humour your request.

It works for me if I stick in site-package a pth containing this:

```
import coverage; from coverage import data; data.open = open; coverage.process_startup()
```

Then I set an environ variable: `COVERAGE_PROCESS_START=.coveragerc`

And then in the `.coveragerc` file I have:

```
[run]
parallel = true
source = .
```

Easy peasy lemon squezy :grin:

**Comment by gmunkhbaatarmn** [comment]
Thanks for your posting your solution.

Tried your suggested way. But didn't works for me. Also tried by adding coverage package into project directory. But still not produced coverage data (`.coverage`) files.

**Comment by ionelmc** [comment]
You don't give me much to go on here - you have to post more details (logs, what you did, description of project layout etc) to help characterize the cause.

**Comment by gmunkhbaatarmn** [comment]
Tested project source is: https://gist.github.com/gmunkhbaatarmn/b0339af0b13d01d21ba3
`pth` file located in `/usr/local/lib/python2.7/site-packages/gae.pth`

```
$ pip install coverage
$ pip install appengine-sdk
$ cd <path-to-project-dir>
$ dev_appserver .
```

Then also changed `pth` file's code into:

```
import coverage; from coverage import data; data.open = open; coverage.process_startup(); print "Imported!"
```

dev_appserver's log:

```
Imported!
INFO     2015-05-14 11:10:59,919 sdk_update_checker.py:229] Checking for updates to the SDK.
INFO     2015-05-14 11:11:02,819 sdk_update_checker.py:257] The SDK is up to date.
INFO     2015-05-14 11:11:03,007 api_server.py:190] Starting API server at: http://localhost:49737
INFO     2015-05-14 11:11:03,014 dispatcher.py:192] Starting module "default" running at: http://localhost:8080
INFO     2015-05-14 11:11:03,016 admin_server.py:118] Starting admin server at: http://localhost:8000
Imported!
INFO     2015-05-14 11:11:05,417 module.py:788] default: "GET / HTTP/1.1" 200 15
INFO     2015-05-14 11:11:06,344 module.py:788] default: "GET / HTTP/1.1" 200 15
INFO     2015-05-14 11:11:06,637 module.py:788] default: "GET / HTTP/1.1" 200 15
INFO     2015-05-14 11:11:06,855 module.py:788] default: "GET / HTTP/1.1" 200 15
INFO     2015-05-14 11:11:07,037 module.py:788] default: "GET / HTTP/1.1" 200 15
^CINFO     2015-05-14 11:11:17,852 shutdown.py:45] Shutting down.
INFO     2015-05-14 11:11:17,853 api_server.py:615] Applying all pending transactions and saving the datastore
INFO     2015-05-14 11:11:17,853 api_server.py:618] Saving search indexes
```

**Comment by ionelmc** [comment]
Did you create the `.coveragerc` file?

Thanks,
-- Ionel Cristian Mărieș, http://blog.ionelmc.ro

**Comment by gmunkhbaatarmn** [comment]
Yes, `.coveragerc` file located in project layout.
https://gist.github.com/gmunkhbaatarmn/b0339af0b13d01d21ba3#file-coveragerc

**Comment by ionelmc** [comment]
Did you set the environment variable? It's mandatory.

**Comment by gmunkhbaatarmn** [comment]
Oops, the reason was environment variable. In all of prevous attempts, I've set environment variable. But set only for interactive-shell, and during dev_appserver run can't fetch needed environment variable.

Now it works, and generating coverage data. Thank you for your help and guide.

**Comment by ionelmc** [comment]
You're welcome :grin:

**Comment by gmunkhbaatarmn** [comment]
FYI, found a way to integrate coverage without `pth` file.
1. Set environ variable: `COVERAGE_PROCESS_START=.coveragerc`
2. Start app by this command:  
   `dev_appserver.py ./path-to-app --python_startup_script ./path-to/startup_script.py`
   Source of `startup_script.py` is:  
   `import coverage;from coverage import data;data.open = open;coverage.process_startup()`
3. After stopping (kill) process by `signal.SIGINT` (CTRL-C from terminal) coverage data generated under `.coverage` file.
