### ISSUE TITLE
SVN base

### ISSUE THREAD

**Issue by pombredanne** [ionelmc/python-appengine-sdk#2]
@ionelmc You may not know this but the sources for the Python SDK are there, https://code.google.com/p/googleappengine/source/checkout all with history and such.

**Comment by ionelmc** [comment]
Interesting but I only want to make pypi packages for what they actually release, not what they have on svn. Am I missing something?

**Comment by pombredanne** [comment]
@ionelmc You are not. They actually seem to only sync from some internal repo of theirs to this SVN repo for releases... and do not even care to tag this, so this is not that useful after all...
