### ISSUE TITLE
Using appengine in my own scripts

### ISSUE THREAD

**Issue by tubaman** [ionelmc/python-appengine-sdk#3]
Today, appengine_sdk makes it super easy to run the standard appengine
commands(remote_api_shell, dev_appserver, appcfg).  However in order to
use the appengine libraries in my own scripts, I end up doing something
like this:

``` python
# shennanigans to import appengine
import appengine_sdk
sdk_root = os.path.dirname(appengine_sdk.__file__)
sdk_path = os.path.join(sdk_root, "google_appengine")
if 'GAE_SDK_ROOT' not in os.environ:
    os.environ['GAE_SDK_ROOT'] = sdk_root
    # import paths fixup, just in case
    if 'PYTHONPATH' in os.environ:
        os.environ['PYTHONPATH'] += os.pathsep + sdk_path
    else:
        os.environ['PYTHONPATH'] = sdk_path
    sys.path = [sdk_path] + sys.path

from google.appengine.ext.ndb.key import Key
```

I'd like to contribute code that makes this easier.  My first thought is to just symlink the google package right into dist-packages.  That would make it a standard python package available for import without doing anything crazy.  Thoughts?

**Comment by ionelmc** [comment]
It should already be importable without messing with sys.path. Perhaps an install issue? Do you have `appengine-sdk.pth` in site-packages?

**Comment by tubaman** [comment]
On Fri, Jun 17, 2016 at 12:49:11PM -0700, Ionel Cristian Mărieș wrote:

> It should already be importable without messing with sys.path. Perhaps an install issue? Do you have `appengine-sdk.pth` in site-packages?

You're totally right.  I hadn't properly pip installed in my vagrant VM.
My mistake.
